### ISSUE TITLE
[support] is that support nodejs ?

### ISSUE THREAD

**Issue by JackTn** [xxj95719/custom-json2excel#18]

**Comment by JackTn** [comment]
i use this repo in my nodejs app, when i generate it. This app has no reaction~
```
const json2excel = new Json2excel({ data: data_formant, keyMap: [...data.columns, "a"], orderedKey: ["a"]});
json2excel.generate();
```

**Comment by asasugar** [comment]
I have packaged it into cjs, it should support the node environment, but I have not tried it, you can share your mini repo

**Comment by asasugar** [comment]
> i use this repo in my nodejs app, when i generate it. This app has no reaction~
> 
> ```
> const json2excel = new Json2excel({ data: data_formant, keyMap: [...data.columns, "a"], orderedKey: ["a"]});
> json2excel.generate();
> ```

I have packaged it into cjs, it should support the node environment, but I have not tried it, you can share your mini repo

**Comment by asasugar** [comment]
> > i use this repo in my nodejs app, when i generate it. This app has no reaction~
> > ```
> > const json2excel = new Json2excel({ data: data_formant, keyMap: [...data.columns, "a"], orderedKey: ["a"]});
> > json2excel.generate();
> > ```
> 
> I have packaged it into cjs, it should support the node environment, but I have not tried it, you can share your mini repo
try:  import Json2excel from 'custom-json2excel/dist/index.cjs'

**Comment by asasugar** [comment]
> i use this repo in my nodejs app, when i generate it. This app has no reaction~
> 
> ```
> const json2excel = new Json2excel({ data: data_formant, keyMap: [...data.columns, "a"], orderedKey: ["a"]});
> json2excel.generate();
> ```

try import Json2excel from 'custom-json2excel/dist/index.cjs'
