### ISSUE TITLE
导出字符串数字，前面的 00 没有了

### ISSUE THREAD

**Issue by fangtang0101** [xxj95719/custom-json2excel#19]
导出的时候，设置了 ‘00123’，是字符串，但是导出后，变成了 数字，并且 00 丢失

**Comment by asasugar** [comment]
> 导出的时候，设置了 ‘00123’，是字符串，但是导出后，变成了 数字，并且 00 丢失

最近有点忙，过几天处理一下,hhhh

**Comment by asasugar** [comment]
包名更新了，注意更新包名

**Comment by asasugar** [comment]
能用了，麻烦点个star支持一下
