### ISSUE TITLE
无法下载xls

### ISSUE THREAD

**Issue by ukhack** [xxj95719/custom-json2excel#2]
yarn add custom-json2excel 
调用
let we = [
                    {
                        name: '哈哈',
                        age: 1,
                        sex: '男',
                        companyName: '公司1',
                        companyAddress: '公司地址1'
                    },
                    {
                        name: '呵呵',
                        age: 2,
                        sex: '女',
                        companyName: '公司2',
                        companyAddress: '公司地址2'
                    },
                    {
                        name: '嘻嘻',
                        age: 3,
                        sex: '男',
                        companyName: '公司3',
                        companyAddress: '公司地址3'
                    },
                    {
                        name: '啦啦',
                        age: 4,
                        sex: '女',
                        companyName: '公司4',
                        companyAddress: '公司地址4'
                    }
                ];
                const json2excel = new Json2excel({ we });
                json2excel.generate()；
无法完成下载，没有反应，控制台也无报错。

**Comment by xxj95719** [comment]
这个是对象，你需要传 const json2excel = new Json2excel({ data:we });

**Comment by asasugar** [comment]
> yarn add custom-json2excel
> 调用
> let we = [
> {
> name: '哈哈',
> age: 1,
> sex: '男',
> companyName: '公司1',
> companyAddress: '公司地址1'
> },
> {
> name: '呵呵',
> age: 2,
> sex: '女',
> companyName: '公司2',
> companyAddress: '公司地址2'
> },
> {
> name: '嘻嘻',
> age: 3,
> sex: '男',
> companyName: '公司3',
> companyAddress: '公司地址3'
> },
> {
> name: '啦啦',
> age: 4,
> sex: '女',
> companyName: '公司4',
> companyAddress: '公司地址4'
> }
> ];
> const json2excel = new Json2excel({ we });
> json2excel.generate()；
> 无法完成下载，没有反应，控制台也无报错。

答：这个是对象，你需要传 const json2excel = new Json2excel({ data:we });
