### ISSUE TITLE
feat:可以考虑增加个callback选项吗

### ISSUE THREAD

**Issue by ningxzx** [xxj95719/custom-json2excel#4]
xls文件有点有些大，加个callback方便能加个loading效果，不然就只能监听关掉了。

**Comment by asasugar** [comment]
你是指数据量大的时候，等待时间比较长吗

**Comment by ningxzx** [comment]
> 你是指数据量大的时候，等待时间比较长吗

是的，还可能有别的回调需求嘛

**Comment by asasugar** [comment]
欢迎pr

**Comment by asasugar** [comment]
> > 你是指数据量大的时候，等待时间比较长吗
> 
> 是的，还可能有别的回调需求嘛

新增了两个回调函数 onStart、onSuccess

**Comment by ningxzx** [comment]
> > > 你是指数据量大的时候，等待时间比较长吗
> > 
> > 
> > 是的，还可能有别的回调需求嘛
> 
> 新增了两个回调函数 onStart、onSuccess

Thank you. I'm busy with other projects during these days.
